### ISSUE TITLE
startup failure with Better Badlands (1.16.5)

### ISSUE THREAD

**Issue by Wedge1453** [GoogeTan/FluidAPI#1]
[crash-2021-08-18_10.36.32-fml.txt](https://github.com/GoogeTan/FluidAPI/files/7006197/crash-2021-08-18_10.36.32-fml.txt)

**Comment by StrangerSon71** [comment]
Also happens with Farmer's Delight, Upgrade Aquatic, Structurize.

**Comment by GoogeTan** [comment]
Thanks for your reports, i'll fix it

**Comment by GoogeTan** [comment]
Try 1.16.5-0.0.0.4. It has been fixed on my computer.
