### ISSUE TITLE
Installed This Mod, Opened The World to ALL Fence Gates Being Waterlogged and only being able to be put down Perpendicular

### ISSUE THREAD

**Issue by Morabert** [GoogeTan/FluidAPI#2]
Installing your Mod Waterlogs _ALL_ Fence Gates & When Attempting to Re-instate them they only sit Perpendicular, regardless of crouching, left/right clicking etc. Severely Bugged

**Comment by GoogeTan** [comment]
Fixed since in 0.0.0.4-forge

**Comment by Morabert** [comment]
You sure about that?
![you sure about that](https://user-images.githubusercontent.com/36409264/130404704-4a156ef8-64fc-4607-b2e0-2387aeb56df8.JPG)

**Comment by GoogeTan** [comment]
![2021-08-23_10 50 49](https://user-images.githubusercontent.com/61940455/130410639-748646aa-391c-423f-a405-a5530dc52330.png)
Yes

**Comment by GoogeTan** [comment]
> 
> 
> You sure about that?
> ![you sure about that](https://user-images.githubusercontent.com/36409264/130404704-4a156ef8-64fc-4607-b2e0-2387aeb56df8.JPG)
Is it all mod list? Try to clear mod configs and reinstall mod.

**Comment by GoogeTan** [comment]
Oh... I have cached it.

**Comment by GoogeTan** [comment]
Fixed since 0.0.0.5

**Comment by Morabert** [comment]
> 
> 
> Oh... I have cached it.

_Oooohhh_, Indeed.
