### ISSUE TITLE
Waterlogged property not set to false in default state of brewing stand, enchanting table and anvil

### ISSUE THREAD

**Issue by Fuzss** [GoogeTan/FluidAPI#3]
Brewing stands, enchanting tables and anvils generated during world gen are always waterlogged. In vanilla this can be observed for brewing stands (village, igloo, end city ship) and anvils (woodland mansion) only as enchanting tables don't naturally generate.

To fix this setting the `waterlogged` property to false for the default block state should theoretically work (didn't test this though).
Something like `this.setDefaultState(this.getDefaultState().with(WATERLOGGED, false))` should be added to each constructor with a mixin to achieve this.

**Comment by GoogeTan** [comment]
It was fixed in 0.1.0

**Comment by Fuzss** [comment]
Should be alright, thanks.
